name: DemoBuild

on: 
  workflow_dispatch:



jobs:
  build:
    env:
      buildConfig: Release
    runs-on: ubuntu-latest

    steps:
      
      - name: Echo
        run: echo $buildConfig
      
