name: DemoBuild

on: 
  workflow_dispatch:

env:
  buildConfig: Debug

jobs:
  build:
    env:
      buildConfig: Release
    runs-on: ubuntu-latest

    steps:
      
      - name: Echo
        env:
          buildConfig: Hi
        run: echo $buildConfig
      
