name: DemoBuild

on: [push]

env:
  BUILDCONFIG: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Echo1
        run: echo $BuildConfig

      - name: change var
        run: echo "BuildConfig=Release" >> "$GITHUB_ENV"

      - name: Echo2
        run: echo $BuildConfig
